//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace new_tech
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials_import_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials_import_()
        {
            this.Materials_in_product_import_ = new HashSet<Materials_in_product_import_>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_type_material { get; set; }
        public string name { get; set; }
        public Nullable<int> value_package { get; set; }
        public Nullable<int> id_unit_measurement { get; set; }
        public Nullable<double> cost { get; set; }
    
        public virtual Maerial_type_import_ Maerial_type_import_ { get; set; }
        public virtual Unit_measurement_import_ Unit_measurement_import_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materials_in_product_import_> Materials_in_product_import_ { get; set; }
    }
}
