//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace new_tech
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner_products_request_import_
    {
        public int id { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> id_partner { get; set; }
        public Nullable<int> value_product { get; set; }
    
        public virtual Partners_import_ Partners_import_ { get; set; }
        public virtual Products_import_ Products_import_ { get; set; }
    }
}
