//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace new_tech
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners_import_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners_import_()
        {
            this.Partner_products_request_import_ = new HashSet<Partner_products_request_import_>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_type_partner { get; set; }
        public string name { get; set; }
        public string director { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string adress_partner { get; set; }
        public string INN { get; set; }
        public Nullable<int> rating { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partner_products_request_import_> Partner_products_request_import_ { get; set; }
        public virtual Type_partner_import_ Type_partner_import_ { get; set; }
    }
}
