//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace new_tech
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_import_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products_import_()
        {
            this.Materials_in_product_import_ = new HashSet<Materials_in_product_import_>();
            this.Partner_products_request_import_ = new HashSet<Partner_products_request_import_>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_type_product { get; set; }
        public string name { get; set; }
        public Nullable<int> articul { get; set; }
        public Nullable<double> mincost_forpartner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materials_in_product_import_> Materials_in_product_import_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partner_products_request_import_> Partner_products_request_import_ { get; set; }
        public virtual Product_type_import_ Product_type_import_ { get; set; }
    }
}
